# Generated by Django 5.1.2 on 2024-11-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='static/')),
                ('primary_color', models.CharField(max_length=7)),
                ('text_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream_link', models.CharField(default='https://youtube.com', max_length=255)),
                ('exit_position', models.CharField(choices=[('top', 'Top'), ('left', 'Left'), ('bottom', 'Bottom'), ('right', 'Right')], default='top', max_length=10)),
                ('current_count', models.IntegerField(default=1)),
                ('max_capacity', models.IntegerField(default=1)),
                ('week_history', models.JSONField(default=dict)),
                ('amenities', models.ManyToManyField(related_name='spaces', to='backend.amenity')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='backend.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
    ]
