# Generated by Django 5.1.2 on 2024-11-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='stream_link',
            field=models.CharField(default='https://youtube.com', max_length=255),
        ),
    ]
