# Generated by Django 5.1.2 on 2024-11-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_space_stream_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='exit_position',
            field=models.CharField(choices=[('top', 'Top'), ('left', 'Left'), ('bottom', 'Bottom'), ('right', 'Right')], default='top', max_length=10),
        ),
    ]
